spring:
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 60000
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            scope: openid
            redirect-uri: ${REDIRECT_URI}
            clientName: ${CLIENT_NAME}
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuerUri: ${ISSUER_URI}
            user-name-attribute: username
